# Generated by Django 4.2.1 on 2024-10-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patients',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
