# Generated by Django 4.2.1 on 2025-06-29 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recordshare',
            name='main_record_doctor__d3191d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='recordshare',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='recordshare',
            name='to_user',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_record_shares', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='visibility',
            field=models.CharField(choices=[('draft', 'Draft'), ('shared', 'Shared'), ('confirmed', 'Confirmed')], default='draft', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='recordshare',
            unique_together={('record', 'to_user')},
        ),
        migrations.AddIndex(
            model_name='recordshare',
            index=models.Index(fields=['to_user', 'status'], name='main_record_to_user_7c306f_idx'),
        ),
        migrations.RemoveField(
            model_name='recordshare',
            name='doctor',
        ),
    ]
