# Generated by Django 4.2.1 on 2024-10-20 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_patients_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patients',
            name='content',
        ),
        migrations.CreateModel(
            name='MedHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.patients')),
            ],
        ),
    ]
