# Generated by Django 4.2.1 on 2024-10-20 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_patients_content_medhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medhistory',
            old_name='patient_id',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='medhistory',
            name='time_update',
        ),
        migrations.RemoveField(
            model_name='patients',
            name='is_published',
        ),
    ]
