# Generated by Django 4.2.1 on 2025-06-20 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_patient_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivejob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Когда закончилась обработка'),
        ),
        migrations.AddField(
            model_name='archivejob',
            name='raw_extracted',
            field=models.JSONField(blank=True, default=dict, help_text='Сырые данные разбора архива (все найденные ФИО, даты, телефоны, e-mail и т.п.)'),
        ),
        migrations.AddField(
            model_name='archivejob',
            name='record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archive_job', to='main.medicalrecord'),
        ),
        migrations.AlterField(
            model_name='archivejob',
            name='archive_file',
            field=models.FileField(max_length=500, upload_to='archives/%Y/%m/%d/'),
        ),
    ]
