# Generated by Django 4.2.1 on 2024-10-20 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_patient_id_medhistory_patient_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads_model')),
            ],
        ),
        migrations.AlterField(
            model_name='medhistory',
            name='content',
            field=models.TextField(blank=True, verbose_name='Диагноз'),
        ),
        migrations.AlterField(
            model_name='medhistory',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Опубликовать'),
        ),
        migrations.AlterField(
            model_name='medhistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.patients', verbose_name='Пациент'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='patients',
            name='title',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
    ]
