# Generated by Django 4.2.1 on 2025-06-24 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_patient_options_alter_patient_email_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharerequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sharerequest',
            name='to_email',
            field=models.EmailField(default='example@gmail.com', help_text='Email того, с кем хотим поделиться', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sharerequest',
            name='to_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='sharerequest',
            unique_together={('to_email', 'patient')},
        ),
    ]
