# Generated by Django 5.1.4 on 2024-12-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_patients_photo_alter_patients_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='medhistory',
            name='appointment_location',
            field=models.CharField(default='Клиника Шамова', max_length=255, verbose_name='Место прохождения приёма'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medhistory',
            name='doctor_name',
            field=models.CharField(default='Шамов Салам Меджидович', max_length=255, verbose_name='ФИО доктора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medhistory',
            name='doctor_specialization',
            field=models.CharField(default='Ортодонт', max_length=255, verbose_name='Специальность доктора'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medhistory',
            name='institution_specialization',
            field=models.CharField(default='Стоматологическая клиника', max_length=255, verbose_name='Специализация мед учреждения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medhistory',
            name='lab_data',
            field=models.FileField(blank=True, null=True, upload_to='lab_data/files/%Y/%m/%d', verbose_name='Лабораторные данные (файлы)'),
        ),
        migrations.AddField(
            model_name='patients',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='patients',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Электронная почта'),
        ),
    ]
