# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: docere/eventhub/v1/events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'docere/eventhub/v1/events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x64ocere/eventhub/v1/events.proto\x12\x12\x64ocere.eventhub.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xaa\x01\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\ttenant_id\x18\x02 \x01(\t\x12\x0c\n\x04type\x18\x03 \x01(\t\x12\x10\n\x08\x61\x63tor_id\x18\x04 \x01(\t\x12\x12\n\npatient_id\x18\x05 \x01(\t\x12&\n\x02ts\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12&\n\x05props\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct\"?\n\x13PublishEventRequest\x12(\n\x05\x65vent\x18\x01 \x01(\x0b\x32\x19.docere.eventhub.v1.Event\"3\n\x14PublishEventResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"9\n\x15PublishEventsResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\r\x12\x0e\n\x06\x66\x61iled\x18\x02 \x01(\r2\xc9\x01\n\x0b\x45ventIngest\x12\x61\n\x0cPublishEvent\x12\'.docere.eventhub.v1.PublishEventRequest\x1a(.docere.eventhub.v1.PublishEventResponse\x12W\n\rPublishEvents\x12\x19.docere.eventhub.v1.Event\x1a).docere.eventhub.v1.PublishEventsResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'docere.eventhub.v1.events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EVENT']._serialized_start=119
  _globals['_EVENT']._serialized_end=289
  _globals['_PUBLISHEVENTREQUEST']._serialized_start=291
  _globals['_PUBLISHEVENTREQUEST']._serialized_end=354
  _globals['_PUBLISHEVENTRESPONSE']._serialized_start=356
  _globals['_PUBLISHEVENTRESPONSE']._serialized_end=407
  _globals['_PUBLISHEVENTSRESPONSE']._serialized_start=409
  _globals['_PUBLISHEVENTSRESPONSE']._serialized_end=466
  _globals['_EVENTINGEST']._serialized_start=469
  _globals['_EVENTINGEST']._serialized_end=670
# @@protoc_insertion_point(module_scope)
