# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from eventhub.v1 import events_pb2 as docere_dot_eventhub_dot_v1_dot_events__pb2

GRPC_GENERATED_VERSION = '1.75.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in docere/eventhub/v1/events_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class EventIngestStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PublishEvent = channel.unary_unary(
                '/docere.eventhub.v1.EventIngest/PublishEvent',
                request_serializer=docere_dot_eventhub_dot_v1_dot_events__pb2.PublishEventRequest.SerializeToString,
                response_deserializer=docere_dot_eventhub_dot_v1_dot_events__pb2.PublishEventResponse.FromString,
                _registered_method=True)
        self.PublishEvents = channel.stream_unary(
                '/docere.eventhub.v1.EventIngest/PublishEvents',
                request_serializer=docere_dot_eventhub_dot_v1_dot_events__pb2.Event.SerializeToString,
                response_deserializer=docere_dot_eventhub_dot_v1_dot_events__pb2.PublishEventsResponse.FromString,
                _registered_method=True)


class EventIngestServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PublishEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishEvents(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EventIngestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PublishEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishEvent,
                    request_deserializer=docere_dot_eventhub_dot_v1_dot_events__pb2.PublishEventRequest.FromString,
                    response_serializer=docere_dot_eventhub_dot_v1_dot_events__pb2.PublishEventResponse.SerializeToString,
            ),
            'PublishEvents': grpc.stream_unary_rpc_method_handler(
                    servicer.PublishEvents,
                    request_deserializer=docere_dot_eventhub_dot_v1_dot_events__pb2.Event.FromString,
                    response_serializer=docere_dot_eventhub_dot_v1_dot_events__pb2.PublishEventsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'docere.eventhub.v1.EventIngest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('docere.eventhub.v1.EventIngest', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EventIngest(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PublishEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/docere.eventhub.v1.EventIngest/PublishEvent',
            docere_dot_eventhub_dot_v1_dot_events__pb2.PublishEventRequest.SerializeToString,
            docere_dot_eventhub_dot_v1_dot_events__pb2.PublishEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/docere.eventhub.v1.EventIngest/PublishEvents',
            docere_dot_eventhub_dot_v1_dot_events__pb2.Event.SerializeToString,
            docere_dot_eventhub_dot_v1_dot_events__pb2.PublishEventsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
